### ISSUE TITLE
segmentation fault in `_PyObject_LookupAttr`

### ISSUE THREAD

**Issue by TheOnAndOnlyZenomat** [jchv/nix-binary-ninja#1]
Hey,
When I install the flake it fails to launch, except the help commands.
It fails with `segmentation fault (core dumped)  binaryninja`.

According to gdb the `gdb` the execution fails in `_PyObject_LookupAttr`
```
Thread 1 "binaryninja" received signal SIGSEGV, Segmentation fault.
0x00007fffca5786c9 in _PyObject_LookupAttr ()
   from /nix/store/901c80rlps5q05bnjk1sj4zaz5k736nc-python3-3.12.7/lib/libpython3.12.so.1.0
```

Binaryninja hower itself runs fine, if I start it from the installer, i.e.:
1. Extract `binaryninja_personal_linux.zip`
2. Run it with `NIXPKGS_ALLOW_UNFREE=1 nix-shell -p steam-run --run "steam-run ./binaryninja"`

I'd be happy to help fix this to the best of my abilities, but I probably struggle to debug the nix implementation myself.

**Comment by jchv** [comment]
Unfortunately, I am unable to reproduce this: starting binaryninja succeeds on my machine. I thought maybe I accidentally was picking up a missed dependency with Nix-LD, but even after setting `NIX_LD=` and using a personal Binary Ninja license, both the regular and Wayland variants seem to work fine for me.

Can you copy the output of `nix-info -m`?

**Comment by TheOnAndOnlyZenomat** [comment]
Sure, here it is. Any further debugging you need, let me know

```
» nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241029.807e915`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
```

**Comment by jchv** [comment]
My best guess is maybe there's something in your `$HOME/.binaryninja` folder, like perhaps a CPython extension, that is ABI-incompatible and crashing. I'm not actually sure that's how this works, but are there by any chance plugins in `~/.binaryninja/plugins` already?

**Comment by TheOnAndOnlyZenomat** [comment]
Nope, it was a completely fresh install. `~/.binaryninja/plugins` is empty. And it works using `steam-run` which I find weird. Shouldn't that use the same files?

**Comment by TheOnAndOnlyZenomat** [comment]
I have to correct myself. I just deleted the `.binaryninja` dir and started. It gets to a GUI, but only the license selection. After I select the license it coredumps.
If I use the same `steam-run` command with the binary located in the nix store, it also segfaults. So it seems to be something with the files that get installed by the nix package

**Comment by jchv** [comment]
Yeah, the Nix version of the binary is going to have some wrapper stuff setup, which will cause it to always load from the Nix store. That is intentional.

Unfortunately though, I'm not sure what's going wrong here and I'm not sure how to debug it either. I can't seem to reproduce, and I'm not sure what might cause this. I'm guessing it has somehow to do with differences between our NixOS environments.

**Comment by TheOnAndOnlyZenomat** [comment]
Alright, thanks anyway. Maybe I try to dick around with it myself and get something working. Otherwise I just have to resort to the `steam-run` thing for now

**Comment by TheOnAndOnlyZenomat** [comment]
Ok, I fixed it. I forget to set `inputs.nixpkgs.follows = "nixpkgs";` for the flake input.

**Comment by jchv** [comment]
Interesting: I actually am not sure if that should be strictly necessary, there may very well be a bug here still. This seems to suggest that the system Python is inappropriately conflicting with Python inside the wrapped environment.

It's probably not an issue on my machines because I run bleeding edge unstable everywhere anyways... But this is concerning. I will take a closer look after work.

(The workaround of using follows is acceptable and should be safe though, it just indicates I've bunged something up probably.)
